# Generated by Django 5.2.1 on 2025-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('no2', models.FloatField()),
                ('so2', models.FloatField()),
                ('co', models.FloatField()),
                ('o3', models.FloatField()),
                ('predicted_aqi', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
